PRAGMA foreign_keys=ON;
CREATE TABLE users(id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE,name TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN('admin','employee')),password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,password_iterations INTEGER NOT NULL DEFAULT 210000,enabled INTEGER NOT NULL DEFAULT 1,must_change_password INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE sessions(id_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,csrf_hash TEXT NOT NULL,expires_at TEXT NOT NULL,created_at TEXT NOT NULL,last_seen_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE INDEX sessions_expiry ON sessions(expires_at);
CREATE TABLE contacts(id TEXT PRIMARY KEY,customer_name TEXT NOT NULL,phone TEXT NOT NULL,email TEXT,whatsapp TEXT,facebook TEXT,instagram TEXT,notes TEXT,consent_confirmed INTEGER NOT NULL CHECK(consent_confirmed=1),submitted_by TEXT NOT NULL,submitted_by_name TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(submitted_by) REFERENCES users(id));
CREATE UNIQUE INDEX contacts_phone_unique ON contacts(phone);
CREATE UNIQUE INDEX contacts_email_unique ON contacts(email) WHERE email IS NOT NULL AND email<>'';
CREATE INDEX contacts_created ON contacts(created_at DESC);
CREATE INDEX contacts_employee ON contacts(submitted_by,created_at DESC);
CREATE TABLE login_attempts(key TEXT PRIMARY KEY,count INTEGER NOT NULL,window_started TEXT NOT NULL,blocked_until TEXT);
CREATE TABLE audit_log(id TEXT PRIMARY KEY,actor_id TEXT,actor_name TEXT,action TEXT NOT NULL,target_type TEXT,target_id TEXT,details TEXT,ip_hash TEXT,created_at TEXT NOT NULL);
CREATE INDEX audit_created ON audit_log(created_at DESC);
