import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),input=process.argv[2]||path.join(root,'imports','products.csv'),output=path.join(root,'content','products.json');
const split=value=>String(value||'').split('|').map(x=>x.trim()).filter(Boolean),truth=value=>/^(true|yes|1)$/i.test(String(value||''));
function parse(text){const out=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell=''}else if(/[\r\n]/.test(c)&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))out.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(x=>x.trim()))out.push(row);return out}
if(!fs.existsSync(input))throw new Error('Upload imports/products.csv before running this workflow.');
const table=parse(fs.readFileSync(input,'utf8')),headers=table.shift().map(x=>x.trim()),get=(row,name)=>row[headers.indexOf(name)]?.trim()||'',current=JSON.parse(fs.readFileSync(output,'utf8')),bySku=new Map((current.products||[]).map(p=>[p.sku,p])),seen=new Set();
for(const [index,row] of table.entries()){const name=get(row,'Product Name'),sku=get(row,'Main SKU'),slug=get(row,'Slug'),category=get(row,'Category Slug');if(!name||!sku||!slug||!category)throw new Error(`Row ${index+2}: Product Name, Slug, Main SKU and Category Slug are required.`);if(seen.has(sku))throw new Error(`Row ${index+2}: duplicate SKU ${sku}`);seen.add(sku);const colors=split(get(row,'Colours')),sizes=split(get(row,'Sizes')),variantSkus=split(get(row,'Variant SKUs')),variantStocks=split(get(row,'Variant Stocks')),combos=[];for(const color of colors.length?colors:[''])for(const size of sizes.length?sizes:[''])combos.push({color,size});if(variantSkus.length!==variantStocks.length)throw new Error(`Row ${index+2}: Variant SKU and stock counts differ.`);if(variantSkus.length&&variantSkus.length!==combos.length)throw new Error(`Row ${index+2}: expected ${combos.length} variants.`);const previous=bySku.get(sku)||{},stock=Math.max(0,Number(get(row,'Main Stock'))||0);bySku.set(sku,{...previous,name,slug,description:get(row,'Description'),price:Number(get(row,'Regular Price'))||0,offerPrice:get(row,'Offer Price')?Number(get(row,'Offer Price')):undefined,sku,stock,category,colors,sizes,ageGroup:get(row,'Age Group'),variants:variantSkus.map((v,i)=>({sku:v,color:combos[i]?.color||'',size:combos[i]?.size||'',stock:Math.max(0,Number(variantStocks[i])||0)})),images:split(get(row,'Image URLs or Paths')),material:get(row,'Material'),care:get(row,'Care'),measurements:get(row,'Measurements'),included:get(row,'Included'),deliveryInfo:get(row,'Delivery Info'),returnInfo:get(row,'Return Info'),safetyInfo:get(row,'Safety Info'),featured:truth(get(row,'Featured')),visible:get(row,'Visible')?truth(get(row,'Visible')):true,available:stock>0})}
fs.writeFileSync(output,JSON.stringify({products:[...bySku.values()]},null,2)+'\n');console.log(`Imported ${table.length} rows; ${bySku.size} products total.`);
